backend:
  name: github
  repo: huynhlan21/gatsby-netlify-cms
  branch: main

local_backend: true
media_folder: static/assets
public_folder: /assets

collections:
  - name: new-blog
    label: New Blog
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Slug", name: "slug", widget: "unique-string" }
      # - { label: "Hero Image", name: "hero_image", widget: image }
      - { label: "Hero Image Alt", name: "hero_image_alt", widget: "string" }
      - { label: "Hero Image Text", name: "hero_image_text", widget: "string" }
      - {
          label: "Hero Image Link",
          name: "hero_image_link",
          widget: "unique-string",
        }
      - { label: "Body", name: "body", widget: "markdown" }
